name: johnwick

on:
  push:
    branches: 
      - master
  

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to JohnWick1
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./JohnWick1
          publish_branch: JohnWick1
          cname: cdn.mochanbw.cn
          allow_empty_commit: true
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
